### ISSUE TITLE
Uncaught Error: Setting active pane that is not present in pane container

### ISSUE THREAD

**Issue by jmny** [oggy/tab-switcher#48]
When we use project plus and this plugin, 

1. if we switch from a project A (with files opened) to a project B (with files opened)  
2. and we try to open tab-switch, we have this exception, we also see the tab list from the project A 

**Atom Version**: 1.7.4
**System**: Ubuntu 14.04.4
**Thrown From**: [tab-switcher](https://github.com/oggy/tab-switcher) package, v1.4.0

### Stack Trace

Uncaught Error: Setting active pane that is not present in pane container

```
At /usr/share/atom/resources/app.asar/src/pane-container.js:193

Error: Setting active pane that is not present in pane container
    at PaneContainer.module.exports.PaneContainer.setActivePane (/usr/share/atom/resources/app.asar/src/pane-container.js:193:17)
    at Pane.module.exports.Pane.activate (/usr/share/atom/resources/app.asar/src/pane.js:807:15)
    at TabList.module.exports.TabList.select (/home/louis/.atom/packages/tab-switcher/lib/tab-list.coffee:156:17)
    at atom-workspace.disposable.add.atom.commands.add.tab-switcher:select (/home/louis/.atom/packages/tab-switcher/lib/tab-switcher.coffee:60:60)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -6:19.2.0 core:undo (atom-text-editor.editor.is-focused)
  3x -6:17.1.0 terminal-plus:toggle (atom-text-editor.editor.is-focused)
     -5:31.8.0 core:move-down (atom-text-editor.editor.is-focused)
  7x -5:30.1.0 core:close (atom-text-editor.editor.is-focused)
     -3:58.3.0 project-plus:toggle-project-finder (atom-pane.pane.active)
     -3:50.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:49.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:48.4.0 linter:lint (atom-text-editor.editor.is-focused)
  2x -3:45.4.0 core:move-down (atom-text-editor.editor.is-focused)
 87x -3:44.7.0 core:move-up (atom-text-editor.editor.is-focused)
 29x -3:40 core:move-down (atom-text-editor.editor.is-focused)
 13x -0:10.9.0 core:move-up (atom-text-editor.editor.is-focused)
 33x -0:09.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:07.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:06.1.0 tab-switcher:next (atom-text-editor.editor.is-focused)
     -0:02.2.0 tab-switcher:select (ol.tab-switcher-tab-list)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "git-plus",
      "project-switcher2",
      "atom-jinja2"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.9
atom-typescript, v8.10.2
dockerletion, v0.2.0
language-docker, v1.1.6
linter, v1.11.4
linter-docker, v0.1.2
php-twig, v4.0.0
project-plus, v0.9.0
tab-switcher, v1.4.0
tabs-to-spaces, v1.0.2
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by tchesa** [comment]
same problem. Incompatibility with project-plus package.

**Comment by ThroughLee** [comment]
same here.

**Comment by siebz0r** [comment]
Got the same error today, also with project-plus. Any news on this?
