### ISSUE TITLE
Error thrown on startup

### ISSUE THREAD

**Issue by jonyeezs** [oggy/tab-switcher#55]
This is with the latest atom version since today.

It happens on startup

Wild guess: this could be the problem: https://github.com/atom/atom/pull/12925/commits

**Atom Version**: 1.11.0
**Electron Version**: 0.37.8
**System**: Microsoft Windows Server 2012 R2 Standard
**Thrown From**: [tab-switcher](https://github.com/oggy/tab-switcher) package, v1.5.3

### Stack Trace

Failed to activate the tab-switcher package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (C:\Users\vagrant\AppData\Local\atom\app-1.11.0\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (C:\Users\vagrant\AppData\Local\atom\app-1.11.0\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:43:11)
    at new TabListView (file:///C:/Users/vagrant/.atom/packages/tab-switcher/lib/tab-list-view.coffee:60:17)
    at new TabList (file:///C:/Users/vagrant/.atom/packages/tab-switcher/lib/tab-list.coffee:16:17)
    at Object.TabSwitcher.deserialize (file:///C:/Users/vagrant/.atom/packages/tab-switcher/lib/tab-switcher.coffee:36:34)
    at Object.module.exports.activate (file:///C:/Users/vagrant/.atom/packages/tab-switcher/lib/tab-switcher.coffee:66:19)
    at Package.module.exports.Package.activateNow (C:\Users\vagrant\AppData\Local\atom\app-1.11.0\resources\app.asar\src\package.js:183:20)
    at C:\Users\vagrant\AppData\Local\atom\app-1.11.0\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\vagrant\AppData\Local\atom\app-1.11.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\vagrant\AppData\Local\atom\app-1.11.0\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\vagrant\AppData\Local\atom\app-1.11.0\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\vagrant\AppData\Local\atom\app-1.11.0\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\vagrant\AppData\Local\atom\app-1.11.0\resources\app.asar\src\package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (C:\Users\vagrant\AppData\Local\atom\app-1.11.0\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\vagrant\AppData\Local\atom\app-1.11.0\resources\app.asar\src\package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\vagrant\AppData\Local\atom\app-1.11.0\resources\app.asar\src\package-manager.js:497:46)
    at C:\Users\vagrant\AppData\Local\atom\app-1.11.0\resources\app.asar\src\atom-environment.js:779:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "refactor",
      "symbols-view",
      "omnisharp-atom",
      "json-schema",
      "atom-yeoman",
      "wrap-guide",
      "styleguide"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "jasmine-runner",
      "tree-view",
      "git-time-machine",
      "git-line"
    ],
    "projectHome": "C:\\Development",
    "telemetryConsent": "limited",
    "themes": [
      "atom-material-ui",
      "new-moon-atom-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.4 (inactive)
aligner, v0.22.2 (inactive)
aligner-javascript, v1.0.0 (inactive)
aligner-ruby, v1.5.0 (inactive)
atom-beautify, v0.29.13 (inactive)
atom-material-ui, v1.3.6 (inactive)
atom-ternjs, v0.15.0 (inactive)
atom-visual-studio-code-ui, v1.3.4 (inactive)
autoclose-html, v0.23.0 (inactive)
autocomplete, v0.47.0 (inactive)
autocomplete-paths, v1.0.2 (inactive)
bottom-dock, v0.4.4 (inactive)
clipboard-history, v0.6.6 (inactive)
color-picker, v2.2.2 (inactive)
column-select, v0.2.0 (inactive)
docblockr, v0.8.7 (inactive)
double-tag, v0.4.0 (inactive)
editorconfig, v1.4.1 (inactive)
feedback, v0.38.0 (inactive)
file-icons, v1.7.21 (inactive)
git-history, v3.2.0 (inactive)
git-line, v0.5.0 (inactive)
git-log, v0.4.1 (inactive)
git-time-machine, v1.5.3 (inactive)
gulp-manager, v0.2.19 (inactive)
highlight-selected, v0.11.2 (inactive)
language-batch, v0.3.3 (inactive)
language-cshtml, v0.2.1 (inactive)
language-gherkin, v1.0.4 (inactive)
language-groovy, v0.6.0 (inactive)
language-powershell, v4.0.0 (inactive)
language-puppet, v0.21.0 (inactive)
linter, v1.11.18 (inactive)
linter-eslint, v8.0.0 (inactive)
linter-rubocop, v0.5.0 (inactive)
merge-conflicts, v1.4.4 (inactive)
minimap, v4.25.0 (inactive)
minimap-highlight-selected, v4.4.0 (inactive)
minimap-linter, v1.6.0 (inactive)
minitest-snippets, v0.2.0 (inactive)
new-moon-atom-syntax, v2.0.6 (inactive)
open-in-browser, v0.4.7 (inactive)
open-recent, v5.0.0 (inactive)
pretty-json, v1.6.1 (inactive)
ruby-block, v0.3.5 (inactive)
ruby-bundler, v0.3.0 (inactive)
save-session, v0.16.0 (inactive)
sync-settings, v0.7.2 (inactive)
tab-switcher, v1.5.3 (inactive)
todo-show, v1.7.0 (inactive)
xml-formatter, v0.10.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.2 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.59.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v1.0.0 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.68.2 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.209.3 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.33.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.2 (inactive)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.23.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by jonyeezs** [comment]
Maybe need to do this for the listeners https://github.com/atom/dom-listener?

**Comment by oggy** [comment]
Thanks for the report -- fix pushed!
