### ISSUE TITLE
Uncaught TypeError: Arguments to CompositeDisposable.add must have a .dispose() method

### ISSUE THREAD

**Issue by tautologistics** [oggy/tab-switcher#56]
[Enter steps to reproduce below:]

1. Update to Atom v1.11.x
2. Open Atom and/or attempt to switch tabs

![image](https://cloud.githubusercontent.com/assets/148452/19293660/1edc4206-8ff4-11e6-903e-f290dd468a93.png)

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Mac OS X 10.10.5
**Thrown From**: [tab-switcher](https://github.com/oggy/tab-switcher) package, v1.5.3

### Stack Trace

Uncaught TypeError: Arguments to CompositeDisposable.add must have a .dispose() method

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:43:11)
    at new TabListView (/Users/chris/.atom/packages/tab-switcher/lib/tab-list-view.coffee:60:17)
    at new TabList (/Users/chris/.atom/packages/tab-switcher/lib/tab-list.coffee:16:17)
    at Object.TabSwitcher.currentList (/Users/chris/.atom/packages/tab-switcher/lib/tab-switcher.coffee:13:42)
    at atom-workspace.disposable.add.atom.commands.add.tab-switcher:next (/Users/chris/.atom/packages/tab-switcher/lib/tab-switcher.coffee:58:31)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:02.0 tab-switcher:next (atom-pane.pane.active)
  2x -0:00.8.0 core:cancel (atom-pane.pane.active)
     -0:00.1.0 tab-switcher:next (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "closeEmptyWindows": false,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "remote-sync",
      "linter-jscs",
      "find-selection",
      "advanced-new-file",
      "linter-pylint",
      "emmet",
      "omnisharp-atom",
      "tree-view-open-files",
      "file-type-icons",
      "autohide-tree-view",
      "linter-flow"
    ],
    "projectHome": "/Users/chris/projects",
    "telemetryConsent": "no",
    "themes": [
      "atom-dark-ui",
      "monokai-seti"
    ]
  },
  "tab-switcher": {}
}
```

### Installed Packages

```coffee
# User
advanced-new-file, v0.5.0 (inactive)
advanced-open-file, v0.16.4 (inactive)
aesthetic-ui, v2.0.0 (inactive)
angularjs, v0.3.5 (active)
atom-beautify, v0.29.13 (inactive)
atom-jade, v0.3.0 (active)
atom-ternjs, v0.15.0 (active)
atom-typescript, v10.1.7 (active)
atom-yeoman, v0.3.15 (active)
autocomplete, v0.47.0 (inactive)
autocomplete-modules, v1.6.7 (active)
autohide-tree-view, v0.25.1 (inactive)
color-picker, v2.2.2 (active)
dark-flat-ui, v1.2.4 (inactive)
dash, v1.7.0 (inactive)
daylight-ui, v0.2.2 (inactive)
docker, v0.7.0 (inactive)
editorconfig, v1.4.1 (active)
emmet, v2.4.3 (inactive)
file-icons, v1.7.20 (active)
file-type-icons, v1.3.2 (inactive)
find-selection, v0.16.0 (inactive)
git-control, v0.8.2 (inactive)
git-diff-details, v1.3.0 (active)
git-history, v3.2.0 (inactive)
git-log, v0.4.1 (active)
git-plus, v5.18.0 (active)
git-tab-status, v1.9.2 (active)
git-time-machine, v1.5.3 (inactive)
highlight-selected, v0.11.2 (active)
jade-beautify, v0.1.5 (inactive)
json-schema, vundefined (active)
language-docker, v1.1.7 (active)
language-ejs, v0.4.0 (active)
language-jade, v0.7.2 (active)
language-rust, v0.4.6 (active)
linter, v1.11.18 (active)
linter-bootlint, v1.0.2 (active)
linter-coffeelint, v1.1.2 (active)
linter-csslint, v1.3.3 (active)
linter-docker, v0.1.2 (active)
linter-eslint, v7.3.2 (active)
linter-flow, v5.5.0 (inactive)
linter-htmlhint, v1.3.0 (active)
linter-jade, v0.3.2 (active)
linter-js-yaml, v1.2.5 (active)
linter-jsonlint, v1.3.0 (active)
linter-less, v2.6.0 (active)
linter-markdown, v3.0.2 (active)
linter-php, v1.2.0 (active)
linter-pylint, v1.2.2 (inactive)
linter-rubocop, v0.5.0 (active)
linter-rust, v0.5.7 (active)
linter-sass-lint, v1.7.1 (active)
linter-scss-lint, v3.0.4 (active)
linter-shellcheck, v1.4.1 (active)
linter-tidy, v2.2.0 (active)
linter-tslint, v0.11.1 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-linter, v1.6.0 (active)
monokai-seti, v0.7.0 (active)
native-ui, v0.19.1 (inactive)
omnisharp-atom, v0.30.7 (inactive)
opened-files, v0.3.6 (active)
preview, v0.16.9 (inactive)
project-manager, v3.2.3 (active)
react, v0.16.0 (active)
remote-edit, vundefined (active)
seti-icons, v1.3.4 (active)
seti-ui, v1.3.2 (inactive)
slack-ui, v0.7.0 (inactive)
slim-dark-ui, v0.12.0 (inactive)
sort-lines, v0.14.0 (inactive)
tab-switcher, v1.5.3 (active)
tree-view-git-status, v1.1.0 (active)
tree-view-open-files, v0.3.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by oggy** [comment]
Thanks for the report -- fix pushed!

**Comment by tautologistics** [comment]
Thanks for the quick fix! I actually started on PR this morning before noticing you already closed this 👍
