### ISSUE TITLE
Uncaught TypeError: TabListView.addIcon is not a function

### ISSUE THREAD

**Issue by artisdom** [oggy/tab-switcher#64]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 17.04
**Thrown From**: [tab-switcher](https://github.com/oggy/tab-switcher) package 1.5.5

### Stack Trace

Uncaught TypeError: TabListView.addIcon is not a function

```
At /home/feng/.atom/packages/tab-switcher/lib/tab-list-view.coffee:165

TypeError: TabListView.addIcon is not a function
    at TabListView._makeItem (/packages/tab-switcher/lib/tab-list-view.coffee:165:17)
    at /packages/tab-switcher/lib/tab-list-view.coffee:39:25)
    at /packages/tab-switcher/lib/tab-list.coffee:16:17)
    at Object.currentList (/packages/tab-switcher/lib/tab-switcher.coffee:13:31)
    at /packages/tab-switcher/lib/tab-switcher.coffee:75:35)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at /usr/share/atom/resources/app/src/command-registry.js:3:65
    at Object.didConfirmSelection (/usr/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:106:35)
    at SelectListView.confirmSelection (/usr/share/atom/resources/app/node_modules/atom-select-list/src/select-list-view.js:313:26)
    at HTMLDivElement.core:confirm (/usr/share/atom/resources/app/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at /usr/share/atom/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -3:26 tab-switcher:next (input.hidden-input)
     -3:24.7.0 tab-switcher:previous (input.hidden-input)
  9x -2:00.5.0 core:move-down (div.package-detail.panels-item)
     -1:39.2.0 atom-rtags-plus:find-symbols-by-keyword (div.package-detail.panels-item)
     -1:36.5.0 editor:consolidate-selections (div.package-detail.panels-item)
  7x -1:35.3.0 core:move-down (div.package-detail.panels-item)
  4x -1:33.5.0 core:move-up (div.package-detail.panels-item)
     -0:19.8.0 command-palette:toggle (div.package-detail.panels-item)
     -0:16.7.0 core:confirm (input.hidden-input)
     -0:16.7.0 tab-switcher:next (div.package-detail.panels-item)
     -0:13.6.0 ui:decrease-font-size (div.package-detail.panels-item)
     -0:12 core:cancel (div.package-detail.panels-item)
     -0:10.3.0 command-palette:toggle (div.package-detail.panels-item)
  5x -0:07.1.0 core:move-down (input.hidden-input)
     -0:03.1.0 core:confirm (input.hidden-input)
     -0:03.1.0 tab-switcher:previous (div.package-detail.panels-item)
```

### Non-Core Packages

```
api-docs 0.0.6 
atom-beautify 0.30.4 
atom-clang 1.0.14 
atom-cursor-indent 0.1.1 
atom-rtags 0.2.2 
atom-rtags-plus 1.4.2 
auto-detect-indentation 1.3.0 
autocomplete-clang 0.11.3 
busy-signal 1.4.3 
clang-format 1.29.0 
expose 0.14.0 
gcc-make-run 0.2.11 
git-plus 7.9.3 
git-projects 1.17.0 
git-time-machine 1.5.9 
hey-pane 1.0.0 
highlight-selected 0.13.1 
hyperclick 0.1.3 
intentions 1.1.5 
language-cpp14 0.6.2 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-clang 4.1.2 
linter-ui-default 1.6.3 
minimap 4.29.3 
minimap-highlight-selected 4.6.1 
open-file-in 1.2.3 
pigments 0.39.1 
platformio-ide-terminal 2.5.4 
project-manager 3.3.5 
symbols-tree-nav 0.15.5 
sync-settings 0.8.2 
tab-switcher 1.5.5 
tool-bar 1.1.0 
zentabs 0.8.8 
```

**Comment by oggy** [comment]
Thanks! Fixed in 1.5.6.

FYI if you install the file-icons package you'll also get icons in the tab list.

**Comment by artisdom** [comment]
Thank you for the awesome package.
And with file-icons installed it works great.

**Comment by artisdom** [comment]
Just update to 1.5.6
Working great, thanks.
